#!/usr/bin/env bash
# Render policy/bindings YAML from templates + .env. Never writes secret values.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# shellcheck disable=SC1091
source "${ROOT}/scripts/lib.sh"

require_project
load_versions

trim() {
  local s="$1"
  s="${s#"${s%%[![:space:]]*}"}"
  s="${s%"${s##*[![:space:]]}"}"
  printf '%s' "${s}"
}

is_placeholder() {
  local v="$1"
  [[ -z "${v}" ]] && return 0
  [[ "${v}" == *YOUR_* ]] && return 0
  [[ "${v}" == your-* ]] && return 0
  [[ "${v}" == "owner/repo" ]] && return 0
  [[ "${v}" == "properties/123456789" ]] && return 0
  return 1
}

if [[ -z "${BROKER_URL:-}" ]]; then
  BROKER_URL="$(broker_url)"
fi
export BROKER_URL

# Subjects: CURSOR_OIDC_SUBJECTS (comma-separated) wins; else CURSOR_OIDC_SUBJECT.
SUBJECTS=()
if [[ -n "${CURSOR_OIDC_SUBJECTS:-}" ]]; then
  IFS=',' read -r -a _subjects <<< "${CURSOR_OIDC_SUBJECTS}"
  for s in "${_subjects[@]}"; do
    s="$(trim "${s}")"
    [[ -z "${s}" ]] && continue
    if is_placeholder "${s}"; then
      echo "error: CURSOR_OIDC_SUBJECTS contains a placeholder value: ${s}" >&2
      exit 1
    fi
    SUBJECTS+=("${s}")
  done
elif ! is_placeholder "${CURSOR_OIDC_SUBJECT:-}"; then
  SUBJECTS+=("${CURSOR_OIDC_SUBJECT}")
fi

missing=()
for v in GITHUB_APP_ID GITHUB_APP_INSTALLATION_ID GITHUB_REPOSITORIES GA_PROPERTY_ID; do
  if is_placeholder "${!v:-}"; then
    missing+=("${v}")
  fi
done
if ((${#SUBJECTS[@]} == 0)); then
  missing+=("CURSOR_OIDC_SUBJECT or CURSOR_OIDC_SUBJECTS")
fi

if ((${#missing[@]} > 0)); then
  echo "error: set the following in .env (see .env.example):" >&2
  for v in "${missing[@]}"; do
    echo "  ${v}" >&2
  done
  echo "hint: subjects come from: pade identity --audience ${BROKER_URL}" >&2
  exit 1
fi

GITHUB_REPOSITORIES_YAML=""
IFS=',' read -r -a _repos <<< "${GITHUB_REPOSITORIES}"
for repo in "${_repos[@]}"; do
  repo="$(trim "${repo}")"
  [[ -z "${repo}" ]] && continue
  GITHUB_REPOSITORIES_YAML+="          - ${repo}"$'\n'
done
if [[ -z "${GITHUB_REPOSITORIES_YAML}" ]]; then
  echo "error: GITHUB_REPOSITORIES must list at least one owner/repo" >&2
  exit 1
fi
GITHUB_REPOSITORIES_YAML="${GITHUB_REPOSITORIES_YAML%$'\n'}"

# One policy entry per subject; same capability set (Milestone M A/B dogfood).
CURSOR_OIDC_POLICIES_YAML=""
for subject in "${SUBJECTS[@]}"; do
  CURSOR_OIDC_POLICIES_YAML+="  - subject: \"${subject}\""$'\n'
  CURSOR_OIDC_POLICIES_YAML+="    requireRepoURLs: false"$'\n'
  CURSOR_OIDC_POLICIES_YAML+="    capabilities:"$'\n'
  CURSOR_OIDC_POLICIES_YAML+="      - github.repo.read"$'\n'
  CURSOR_OIDC_POLICIES_YAML+="      - google-analytics.read"$'\n'
  CURSOR_OIDC_POLICIES_YAML+="      - vercel.diagnostics"$'\n'
done
CURSOR_OIDC_POLICIES_YAML="${CURSOR_OIDC_POLICIES_YAML%$'\n'}"

OUT_DIR="${ROOT}/config/.generated"
mkdir -p "${OUT_DIR}"

render_template() {
  local tmpl="$1"
  local dest="$2"
  local content
  content="$(<"${tmpl}")"
  content="${content//\$\{BROKER_URL\}/${BROKER_URL}}"
  content="${content//\$\{CURSOR_OIDC_POLICIES_YAML\}/${CURSOR_OIDC_POLICIES_YAML}}"
  content="${content//\$\{GITHUB_APP_ID\}/${GITHUB_APP_ID}}"
  content="${content//\$\{GITHUB_APP_INSTALLATION_ID\}/${GITHUB_APP_INSTALLATION_ID}}"
  content="${content//\$\{GA_PROPERTY_ID\}/${GA_PROPERTY_ID}}"
  content="${content//\$\{GITHUB_REPOSITORIES_YAML\}/${GITHUB_REPOSITORIES_YAML}}"
  cat > "${dest}" <<EOF
# Generated by make render-config — do not edit.
# Source: $(basename "${tmpl}") + .env
${content}
EOF
}

render_template "${ROOT}/config/broker-policy.yaml.tmpl" "$(policy_file)"
render_template "${ROOT}/config/broker-bindings.yaml.tmpl" "$(bindings_file)"

echo "==> Rendered $(policy_file_rel)"
echo "==> Rendered $(bindings_file_rel)"
echo "    audience=${BROKER_URL}"
echo "    subjects=${SUBJECTS[*]}"
