#!/usr/bin/env bash
# Render policy/bindings YAML from templates + .env. Never writes secret values.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# shellcheck disable=SC1091
source "${ROOT}/scripts/lib.sh"

require_project
load_versions

trim() {
  local s="$1"
  s="${s#"${s%%[![:space:]]*}"}"
  s="${s%"${s##*[![:space:]]}"}"
  printf '%s' "${s}"
}

is_placeholder() {
  local v="$1"
  [[ -z "${v}" ]] && return 0
  [[ "${v}" == *YOUR_* ]] && return 0
  [[ "${v}" == your-* ]] && return 0
  [[ "${v}" == "owner/repo" ]] && return 0
  [[ "${v}" == "properties/123456789" ]] && return 0
  return 1
}

if [[ -z "${BROKER_URL:-}" ]]; then
  BROKER_URL="$(broker_url)"
fi
export BROKER_URL

missing=()
for v in GITHUB_APP_ID GITHUB_APP_INSTALLATION_ID GITHUB_REPOSITORIES GA_PROPERTY_ID CURSOR_OIDC_SUBJECT; do
  if is_placeholder "${!v:-}"; then
    missing+=("${v}")
  fi
done

if ((${#missing[@]} > 0)); then
  echo "error: set the following in .env (see .env.example):" >&2
  for v in "${missing[@]}"; do
    echo "  ${v}" >&2
  done
  echo "hint: CURSOR_OIDC_SUBJECT comes from: pade identity --audience ${BROKER_URL}" >&2
  exit 1
fi

GITHUB_REPOSITORIES_YAML=""
IFS=',' read -r -a _repos <<< "${GITHUB_REPOSITORIES}"
for repo in "${_repos[@]}"; do
  repo="$(trim "${repo}")"
  [[ -z "${repo}" ]] && continue
  GITHUB_REPOSITORIES_YAML+="          - ${repo}"$'\n'
done
if [[ -z "${GITHUB_REPOSITORIES_YAML}" ]]; then
  echo "error: GITHUB_REPOSITORIES must list at least one owner/repo" >&2
  exit 1
fi
GITHUB_REPOSITORIES_YAML="${GITHUB_REPOSITORIES_YAML%$'\n'}"

OUT_DIR="${ROOT}/config/.generated"
mkdir -p "${OUT_DIR}"

render_template() {
  local tmpl="$1"
  local dest="$2"
  local content
  content="$(<"${tmpl}")"
  content="${content//\$\{BROKER_URL\}/${BROKER_URL}}"
  content="${content//\$\{CURSOR_OIDC_SUBJECT\}/${CURSOR_OIDC_SUBJECT}}"
  content="${content//\$\{GITHUB_APP_ID\}/${GITHUB_APP_ID}}"
  content="${content//\$\{GITHUB_APP_INSTALLATION_ID\}/${GITHUB_APP_INSTALLATION_ID}}"
  content="${content//\$\{GA_PROPERTY_ID\}/${GA_PROPERTY_ID}}"
  content="${content//\$\{GITHUB_REPOSITORIES_YAML\}/${GITHUB_REPOSITORIES_YAML}}"
  cat > "${dest}" <<EOF
# Generated by make render-config — do not edit.
# Source: $(basename "${tmpl}") + .env
${content}
EOF
}

render_template "${ROOT}/config/broker-policy.yaml.tmpl" "$(policy_file)"
render_template "${ROOT}/config/broker-bindings.yaml.tmpl" "$(bindings_file)"

echo "==> Rendered $(policy_file_rel)"
echo "==> Rendered $(bindings_file_rel)"
echo "    audience=${BROKER_URL}"
echo "    subject=${CURSOR_OIDC_SUBJECT}"
